- name: Install Apache Cassandra
  hosts: server1
  become: yes
  gather_facts: yes

  vars:
    java_apt_package: openjdk-11-jre
    cassandra_repo_url: "deb https://debian.cassandra.apache.org 41x main"
    cassandra_repo_key_url: "https://downloads.apache.org/cassandra/KEYS"
    cassandra_version: "4.1.3"

  tasks:
    - name: Install Java
      apt:
        name: "{{ java_apt_package }}"
        state: present
        update_cache: yes

    - name: Add Cassandra repository key
      apt_key:
        url: "{{ cassandra_repo_key_url }}"
        state: present

    - name: Add Cassandra repository
      apt_repository:
        repo: "{{ cassandra_repo_url }}"
        state: present

    - name: Download specific Cassandra version
      apt:
        update_cache: yes
        name: "cassandra={{ cassandra_version }}"
        state: present
      tags: install cassandra

    - name: Start and enable Cassandra service
      systemd:
        name: cassandra
        state: started
        enabled: yes
      register: status
    
    - name: status cassandra
      debug:
        var: status
